### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by HackWidMaddy** [0xless/433mhz_jam#1]
Here u r sending freq of 20000Mhz ig will it interfere will all other frequencies including wifi which is working on 2.4GHz and what all freq will be affected?

**Comment by 0xless** [comment]
Hi, thanks for showing interest into this project.

I think the line of code you're referring to is: `tone(out_pin, 20000); // send square wave on pin`.
This function, as described in the [documentation](https://www.arduino.cc/reference/en/language/functions/advanced-io/tone/), generates a square wave of the specified frequency (in hertz).

This signal only represents the data transmitted by the jammer and in no way influences the transmission frequency.
Functionally, it is equivalent to transmitting a specific note on a specific radio frequency. Changing the note, doesn't change the transmission frequency.

If you are preoccupied by interferences, make sure to fully understand how radio communication works and always use the jammer in an isolated environment.
